import {
  AVAX_CHAIN_ID,
  AVAX_TEST_CHAIN_ID,
  BSCTEST_CHAIN_ID,
  BSC_CHAIN_ID,
  ChainId,
  GOERLI_CHAIN_ID,
  KLAYTN_BAOBAB_CHAIN_ID,
  KLAYTN_CYPRESS_CHAIN_ID,
  KOVAN_CHAIN_ID,
  MAINNET_CHAIN_ID,
  POLYGON_CHAIN_ID,
  POLYGON_MUMBAI_CHAIN_ID,
  ROPSTEN_CHAIN_ID,
} from '@constants/network';
import {
  SINGLE_CALL_BALANCES_ADDRESS_AVALANCHE_MAINNET,
  SINGLE_CALL_BALANCES_ADDRESS_AVALANCHE_TESTNET,
  SINGLE_CALL_BALANCES_ADDRESS_BSC_MAINNET,
  SINGLE_CALL_BALANCES_ADDRESS_BSC_TESTNET,
  SINGLE_CALL_BALANCES_ADDRESS_ETH_GOERLI,
  SINGLE_CALL_BALANCES_ADDRESS_ETH_KOVAN,
  SINGLE_CALL_BALANCES_ADDRESS_ETH_MAINNET,
  SINGLE_CALL_BALANCES_ADDRESS_ETH_ROPSTEN,
  SINGLE_CALL_BALANCES_ADDRESS_KLAYTN_BAOBAB,
  SINGLE_CALL_BALANCES_ADDRESS_KLAYTN_CYPRESS,
  SINGLE_CALL_BALANCES_ADDRESS_POLYGON_MAINNET,
  SINGLE_CALL_BALANCES_ADDRESS_POLYGON_TESTNET,
} from './contracts';

export function getContractAddress(chainId: ChainId | string) {
  let contractAddress: string | undefined;
  switch (chainId) {
    case MAINNET_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_ETH_MAINNET;
      break;
    case GOERLI_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_ETH_GOERLI;
      break;
    case KOVAN_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_ETH_KOVAN;
      break;
    case ROPSTEN_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_ETH_ROPSTEN;
      break;
    case BSC_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_BSC_MAINNET;
      break;
    case BSCTEST_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_BSC_TESTNET;
      break;
    case POLYGON_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_POLYGON_MAINNET;
      break;
    case POLYGON_MUMBAI_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_POLYGON_TESTNET;
      break;
    case AVAX_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_AVALANCHE_MAINNET;
      break;
    case AVAX_TEST_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_AVALANCHE_TESTNET;
      break;
    case KLAYTN_CYPRESS_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_KLAYTN_CYPRESS;
      break;
    case KLAYTN_BAOBAB_CHAIN_ID:
      contractAddress = SINGLE_CALL_BALANCES_ADDRESS_KLAYTN_BAOBAB;
      break;
    default:
      break;
  }
  return contractAddress;
}
