export const defaultPreferencesState = {
  frequentRpcList: [],
  frequentRpcListDetail: [],
  accountTokens: {},
  managingTokens: {},
  accountNfts: {},
  assetImages: {},
  accountAssets: {},
  tokens: [],
  suggestedTokens: {},
  useBlockie: false,
  useNonceField: false,
  usePhishDetect: true,
  dismissSeedBackUpReminder: false,
  useStaticTokenList: false,
  featureFlags: {
    showIncomingTransactions: true,
  },
  knownMethodData: {},
  firstTimeFlowType: null,
  currentLocale: '',
  identities: {},
  lostIdentities: {},
  forgottenPassword: false,
  preferences: {
    autoLockTimeLimit: undefined,
    showFiatInTestnets: false,
    useNativeCurrencyAsPrimaryCurrency: true,
    hideZeroBalanceTokens: false,
  },
  completedOnboarding: false,
  ipfsGateway: 'dweb.link',
  infuraBlocked: null,
  useLedgerLive: false,
  selectedAccountKey: '',
  selectedAddress: '',
  selectedBtcAddress: '',
  tokensOrder: {},
  nativeCoinInvisible: {},
  isSupportTestNetworks: false,
  currencyType: 'usd',
  lastNftsSavedDateTime: {},
  homeSelectedChainId: undefined,
  createWalletCount: 0,
  accountFcmData: {},
};
