export const defaultPreferencesState = {
  frequentRpcList: [],
  accountTokens: {},
  managingTokens: {},
  accountNfts: {},
  // assetImages: {},
  // accountAssets: {},
  tokens: [],
  suggestedTokens: {},
  currentLocale: '',
  identities: {},
  lostIdentities: {},
  preferences: {
    autoLockTimeLimit: undefined,
    showFiatInTestnets: false,
    useNativeCurrencyAsPrimaryCurrency: true,
    hideZeroBalanceTokens: false,
  },
  ipfsGateway: 'dweb.link',
  selectedAccountKey: '',
  selectedAddress: '',
  selectedBtcAddress: '',
  tokensOrder: {},
  isSupportTestNetworks: false,
  currencyType: 'usd',
  createWalletCount: 0,
};
